# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Super Art Studio'
tagline:          'Personal website of leoï¼ superarts.org'
description:      'www.superarts.org'
url:              'http://www.superarts.org'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/


# Author Details
author:         'Leo L.'

#Social Media links
linkedin:       'https://www.linkedin.com/in/superarts'
twitter:        'https://twitter.com/superarts_org'
facebook:       'https://www.facebook.com/leo.superarts'
gplus:          'https://plus.google.com/106764261037553798296/'

# Google Analytics
gahandler: 'UA-4585175-5'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right.
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble:
  email: 'leo@superarts.org'
  facebook: 'leo.superarts'
  flickr:
  github: 'superarts'
  instagram:
  linkedin: 'superarts'
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: '106764261037553798296'
  twitter: 'superarts_org'
  stackoverflow: 'users/772295/superarts-org'

# Disqus
disqushandler: 'superarts'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          1.0
